name: CI

on: [push]

jobs:

  client:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sc') }}

      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: client/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      - uses: olafurpg/setup-scala@v7
        with:
          java-version: graalvm@

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build client (scala)
        run: ./mill client.fullOpt

      - name: Build client (js)
        run: npm run package

      - name: Deploy client
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./out/client/webpack/prod
